Array


In [1]:
# 1D array
import numpy as np
a=[1,2,3]
print(np.array(a))

[1 2 3]


In [2]:
# 2D array
import numpy as np
x=np.array([[1,2,3,4],[1,2,3,4]])
print(x)
print(f"{x.ndim}D")


[[1 2 3 4]
 [1 2 3 4]]
2D


In [3]:
# 3D array
import numpy as np
x=np.array([[[1,2,3],[4,5,7],[4,3,2]]])
print(x)


[[[1 2 3]
  [4 5 7]
  [4 3 2]]]
