SOME MORE METHODS OF ARRAY

In [2]:
import numpy as np
x=[[1,2,3,4,5],[3,5,6,7,3]]
arr=np.array(x)
print(arr)


[[1 2 3 4 5]
 [3 5 6 7 3]]


In [6]:
print(arr[0])

[1 2 3 4 5]


In [8]:
print("Second element on first row: ",arr[0,1])

Second element on first row:  2


In [7]:
print(arr[0]+arr[1])

[ 4  7  9 11  8]
