3D ARRAY

In [1]:
import numpy as np
brr=np.array([[[1,2,3],[11,12,13],[15,29,30]]])
print(brr)

[[[ 1  2  3]
  [11 12 13]
  [15 29 30]]]


In [ ]:
brr[block,row,column]-->brr[0,1,2]
1.brr[0]: Selects the first (and only) block[whole matrices]
2.brr[1]:select the second row [11,12,13]
3.brr[2]:select the third element

In [2]:
print(brr[0,1,2])
print(brr[0,2,2])

13
30
