COPY & VIEW

In [19]:
import numpy as np
x=[1,2,3]
array=np.array(x)

In [ ]:
copied_array=array.copy()
array[0]=90
print(array)
print(copied_array)

[90  2  3]
[1 2 3]


The copy SHOULD NOT be affected by the changes made to the original array.

In [21]:
view_array=array.view()
array[0]=90
print(array)
print(view_array)

[90  2  3]
[90  2  3]


The view SHOULD be affected by the changes made to the original array.