SHAPES

In [ ]:
import numpy as np
x=[[1,22,2],[76,3,3]]
array=np.array(x)
print(array)
print(array.flatten())


[[ 1 22  2]
 [76  3  3]]


In [3]:
print(array.shape)

(2, 3)


RESHAPE

In [6]:
print(array.reshape(1,6))

[[ 1 22  2 76  3  3]]


FLATTEN

NameError: name 'array' is not defined