JOINS

In [ ]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
concatenate=np.concatenate((x,y))
print(concatenate)

[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print()
print(arr2)
arr = np.concatenate((arr1, arr2), axis=1)
print()
print(arr)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
