In [9]:
import numpy as np
x=[1,2,3,4]
y=[9,7,6,3]
arr1=np.array(x)
arr2=np.array(y)
print(np.stack((arr1,arr2),axis=1))

[[1 9]
 [2 7]
 [3 6]
 [4 3]]


SHAPE ALONG VERTICAL COLUMNS

In [ ]:
print(np.vstack((arr1,arr2)))

[[1 2 3 4]
 [9 7 6 3]]


SHAPE ALONG ROW

In [10]:
print(np.hstack((arr1,arr2)))

[1 2 3 4 9 7 6 3]


SHAPE ALONG DEPTH(HEIGHT)

In [11]:
print(np.dstack((arr1,arr2)))

[[[1 9]
  [2 7]
  [3 6]
  [4 3]]]
