WHERE (POSITION)

In [ ]:
import numpy as np
x=[19,28,23,4,55,98]
arr=np.array(x)
print(arr)

[19 28 23  4 55 98]


In [4]:
print(np.where(arr==55))

(array([4]),)


In [5]:
print(np.where(arr%2==0))

(array([1, 3, 5]),)
