In [ ]:
import numpy as np
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

In [11]:
sum_up_1=np.sum(sales_data,axis=0)
sum_up=np.sum(sales_data[:,1:],axis=0)

print(sum_up_1)
print(sum_up)
min_sales_c=np.min(sales_data[:,1:],axis=0)#according to column
print(min_sales_c)
min_sales_r=np.min(sales_data[:,1:],axis=1)#according to row
print(min_sales_r)


[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[120000 140000 160000 190000]
[150000 120000 200000 180000 160000]


In [13]:
max_sales_c=np.max(sales_data[:,1:],axis=0)#according to column
print(max_sales_c)
max_sales_r=np.max(sales_data[:,1:],axis=1)#according to row
print(max_sales_r)

[200000 230000 260000 300000]
[250000 190000 300000 270000 230000]
