## SET

In [2]:
import numpy as np
arr=np.array([1,1,1,1,5,6,7,7,8,3,4,888,3,3,3])
print(np.unique(arr))

[  1   3   4   5   6   7   8 888]


## FINDING UNION

In [5]:
import numpy as np
x=np.array([2,34,7,3,9])
y=np.array([4,34,9,3,2])
print(np.union1d(x,y))


[ 2  3  4  7  9 34]


## FINDING INTERSECTION

In [6]:
import numpy as np
x=np.array([2,34,7,3,9])
y=np.array([4,34,9,3,2])
print(np.intersect1d(x,y))


[ 2  3  9 34]


## SET DIFFERENCE

In [9]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]
