RANDOM NUMBER


In [9]:
from numpy import random as rd
print(rd.randint(1,100))


24


In [10]:
print(rd.rand(1,10))

[[0.81296441 0.29025214 0.64810342 0.64903959 0.6524222  0.57103406
  0.15514065 0.0953434  0.64700876 0.65695319]]


In [18]:
from numpy import random as rd
x=rd.rand(2)
print(x)

[0.42086923 0.78437845]


In [19]:
from numpy import random as rd
x=rd.rand(2,3)
print(x)

[[0.85847659 0.41301596 0.06780118]
 [0.62313589 0.10622069 0.937258  ]]


In [28]:
x=rd.choice([2,4,6,8,10])
print(x)

8


In [30]:
x=rd.choice([2,4,6,8,10],size=(2,3))
print(x)

[[10  2 10]
 [ 4  8  4]]


In [31]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 5 5 7 5 5 3 7 7 7 7 3 7 5 7 5 7 5 5 7 7 7 7 7 7 7 5 7 5 7 7 7 5 5 5 5 3
 7 7 7 5 5 7 5 7 7 3 5 3 5 5 7 7 7 7 7 5 7 7 7 7 7 5 7 7 5 7 7 7 3 7 7 7 7
 7 5 7 7 7 7 7 7 5 7 7 5 7 7 5 7 3 5 7 7 7 7 7 7 7 7]
